- name: install redis-server dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: [lsb-release, curl, gpg]

- name: Add an Apt PGP PUBLIC KEY, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://packages.redis.io/gpg
    keyring: /etc/apt/trusted.gpg.d/redis-server.gpg
    state: present

- name: Add the Redis APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/redis-server.gpg] https://packages.redis.io/deb {{ ansible_distribution_release }} main"
    state: present
