---
# handlers file for redis-server
- name: Restart redis-server
  ansible.builtin.systemd:
    name: redis-server
    state: restarted
  become: true
  tags: redis-server

- name: Restart prometheus-redis-exporter
  ansible.builtin.systemd:
    name: prometheus-redis-exporter
    state: restarted
  become: true
  tags: prometheus-redis-exporter

- name: Restart zabbix-agent
  ansible.builtin.systemd:
    name: zabbix-agent2
    state: restarted
  become: true
  tags: zabbix-agent
